on: [push]

name: Cross-compile

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        type: [linux-x64, linux-x86, mac, windows-x64, windows-x86]
        include:
          - type: linux-x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: x86_64-linux-rustdsplit
            path: target/x86_64-unknown-linux-musl/release/rustdsplit
          - type: linux-x86
            os: ubuntu-latest
            target: i686-unknown-linux-musl
            name: x86-linux-rustdsplit
            path: target/i686-unknown-linux-musl/release/rustdsplit
          - type: mac
            os: macos-latest
            target: x86_64-apple-darwin
            name: x86_64-macos-rustdsplit
            path: target/x86_64-apple-darwin/release/rustdsplit
          - type: windows-x64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            name: x86_64-windows-rustdsplit.exe
            path: target\x86_64-pc-windows-msvc\release\rustdsplit.exe
          - type: windows-x86
            os: windows-latest
            target: i686-pc-windows-msvc
            name: x86-windows-rustdsplit.exe
            path: target\i686-pc-windows-msvc\release\rustdsplit.exe
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.path }}
